services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
      - "8081:3000"
    networks:
      - shopswift-network
    restart: unless-stopped

networks:
  shopswift-network:
    external: true
    name: shopswift-network
