"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'vi'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Header/Navigation
    'nav.allProducts': 'All Products',
    'nav.collections': 'Collections',
    'nav.about': 'About',
    'nav.signIn': 'Sign In',
    'nav.signOut': 'Sign Out',
    'nav.myAccount': 'My Account',
    'nav.myOrders': 'My Orders',
    'nav.adminPanel': 'Admin Panel',
    'nav.createAccount': 'Create Account',
    'nav.cart': 'Cart',
    'nav.search': 'Search',
    'nav.shopNav': 'SHOP',
    'nav.collectionNav': 'COLLECTION',
    'nav.aboutNav': 'ABOUT',
    'nav.searchNav': 'SEARCH',
    'nav.cartNav': 'CART',
    'nav.messengerNav': 'MESSENGER',
    'nav.accountNav': 'ACCOUNT',
    'nav.logoutNav': 'LOGOUT',
    'nav.loginNav': 'LOGIN',
    'nav.shopAll': 'ALL',
    'nav.shopTops': 'TOPS',
    'nav.shopShirts': 'SHIRTS',
    'nav.shopJackets': 'JACKETS & COATS',
    'nav.shopSkirts': 'SKIRTS',
    'nav.shopPants': 'PANTS',
    'nav.shopAccessories': 'ACCESSORIES',
    
    // Login/Auth
    'auth.signIn': 'Sign In',
    'auth.adminPortal': 'Admin Portal',
    'auth.accountName': 'Account Name',
    'auth.password': 'Password',
    'auth.forgotPassword': 'Forgot password?',
    'auth.signingIn': 'Signing In...',
    'auth.authenticating': 'Authenticating...',
    'auth.signInAsAdmin': 'Sign In as Admin',
    'auth.adminLogin': 'Admin Login',
    'auth.adminLoginDesc': 'Sign in to access the administration panel',
    'auth.backToUserLogin': '← Back to User Login',
    'auth.needHelp': 'Need help?',
    'auth.contactSupport': 'Contact Support',
    'auth.dontHaveAccount': "Don't have an account?",
    'auth.createOne': 'Create one',
    'auth.email': 'Email',
    'auth.emailRequired': 'Email is required',
    'auth.emailPlaceholder': 'Enter your email address',
    'auth.forgotPasswordDesc': 'Enter your email address and we will send you a link to reset your password.',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.sending': 'Sending...',
    'auth.resetLinkSent': 'Reset link has been sent to your email',
    'auth.resetError': 'Failed to send reset link',
    'auth.backToLogin': 'Back to Login',
    'auth.backToAccount': 'Back to account',
    'auth.changePassword': 'Change Password',
    'auth.currentPassword': 'Current Password',
    'auth.newPassword': 'New Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.currentPasswordRequired': 'Current password is required',
    'auth.newPasswordRequired': 'New password is required',
    'auth.newPasswordMinLength': 'New password must be at least 6 characters',
    'auth.confirmPasswordRequired': 'Confirm password is required',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.passwordChangeSuccess': 'Password changed successfully',
    'auth.passwordChangeError': 'Failed to change password',
    'auth.changingPassword': 'Changing password...',
    'auth.sessionExpired': 'Session expired, please login again',
    'auth.tokenRefreshed': 'Session refreshed successfully',
    'auth.tokenRefreshFailed': 'Failed to refresh session',
    'auth.accountNamePlaceholder': 'Enter your account name',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.accountNameRequired': 'Account name is required!',
    'auth.passwordRequired': 'Password is required!',
    'auth.loginFailed': 'Login failed!',
    'auth.welcomeBack': 'Welcome back, {name}!',
    'auth.backToHome': '← Back to Home',
    
    // Logout Modal
    'logout.confirmTitle': 'Confirm Logout',
    'logout.confirmMessage': 'Are you sure you want to sign out?',
    'logout.confirmButton': 'Sign Out',
    'logout.cancelButton': 'Cancel',
    'logout.success': 'Logged out successfully',
    'logout.failed': 'Logout failed',
    'logout.signingOut': 'Signing out...',
    
    // Admin
    'admin.dashboard': 'Dashboard',
    'admin.products': 'Products',
    'admin.categories': 'Categories',
    'admin.orders': 'Orders',
    'admin.users': 'Users',
    'admin.inventory': 'Inventory',
    'admin.shipping': 'Shipping',
    'admin.promotions': 'Promotions',
    'admin.suppliers': 'Suppliers',
    'admin.content': 'Content',
    'admin.messages': 'Messages',
    'admin.analytics': 'Analytics',
    'admin.payments': 'Payments',
    'admin.tracking': 'Tracking',
    'admin.reviews': 'Reviews',
    'admin.settings': 'Settings',
    'admin.profileSettings': 'Profile Settings',
    
    // Categories
    'categories.title': 'Category Management',
    'categories.addNew': 'Add New Category',
    'categories.edit': 'Edit Category',
    'categories.name': 'Category Name',
    'categories.parent': 'Parent Category',
    'categories.position': 'Position',
    'categories.status': 'Status',
    'categories.active': 'Active',
    'categories.inactive': 'Inactive',
    'categories.actions': 'Actions',
    'categories.noParent': 'No Parent (Main Category)',
    'categories.createSuccess': 'Category created successfully',
    'categories.updateSuccess': 'Category updated successfully',
    'categories.deleteSuccess': 'Category deleted successfully',
    'categories.statusToggled': 'Category status updated',
    'categories.confirmDelete': 'Are you sure you want to delete this category?',
    'categories.deleteWarning': 'This action cannot be undone.',
    'categories.nameRequired': 'Category name is required',
    'categories.loading': 'Loading categories...',
    'categories.noCategories': 'No categories found',

    // Products
    'products.title': 'Products Management',
    'products.addNew': 'Add New Product',
    'products.editProduct': 'Edit Product',
    'products.deleteProduct': 'Delete Product',
    'products.name': 'Product Name',
    'products.slug': 'URL Slug',
    'products.description': 'Description',
    'products.shortDescription': 'Short Description',
    'products.category': 'Category',
    'products.brand': 'Brand',
    'products.material': 'Material',
    'products.status': 'Status',
    'products.featured': 'Featured',
    'products.price': 'Price',
    'products.stock': 'Stock',
    'products.variants': 'Variants',
    'products.images': 'Images',
    'products.actions': 'Actions',
    'products.active': 'Active',
    'products.inactive': 'Inactive',
    'products.outOfStock': 'Out of Stock',
    'products.yes': 'Yes',
    'products.no': 'No',
    'products.confirmDelete': 'Are you sure you want to delete this product?',
    'products.deleteWarning': 'This action cannot be undone.',
    'products.save': 'Save',
    'products.cancel': 'Cancel',
    'products.delete': 'Delete',
    'products.edit': 'Edit',
    'products.view': 'View',
    'products.loading': 'Loading...',
    'products.noProducts': 'No products found',
    'products.createSuccess': 'Product created successfully',
    'products.updateSuccess': 'Product updated successfully',
    'products.deleteSuccess': 'Product deleted successfully',
    'products.error': 'An error occurred',
    'products.searchPlaceholder': 'Search products...',
    'products.filterByCategory': 'Filter by Category',
    'products.filterByStatus': 'Filter by Status',
    'products.sortBy': 'Sort by',
    'products.sortByName': 'Name',
    'products.sortByDate': 'Date Created',
    'products.sortByPrice': 'Price',
    'products.sortByStock': 'Stock',
    'products.sortAsc': 'Ascending',
    'products.sortDesc': 'Descending',
    'products.size': 'Size',
    'products.color': 'Color',
    'products.sku': 'SKU',
    'products.addVariant': 'Add Variant',
    'products.removeVariant': 'Remove Variant',
    'products.addImage': 'Add Image',
    'products.removeImage': 'Remove Image',
    'products.imageUrl': 'Image URL',
    'products.altText': 'Alt Text',
    'products.isPrimary': 'Primary Image',
    'products.displayOrder': 'Display Order',
    'products.metaTitle': 'Meta Title',
    'products.metaDescription': 'Meta Description',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.reset': 'Reset',

    // Account (/account — Orders, Profile, Addresses)
    'account.title': 'Account',
    'account.tabOrders': 'Orders',
    'account.tabProfile': 'Profile',
    'account.tabAddresses': 'Addresses',
    'account.firstName': 'First name',
    'account.lastName': 'Last name',
    'account.email': 'Email',
    'account.phone': 'Phone',
    'account.phoneHint': 'Up to 10 digits, starts with 0 (e.g. 0912345678)',
    'account.emailPlaceholder': 'example@gmail.com',
    'account.passwordSection': 'Password',
    'account.passwordChangeHint': 'Change your account password',
    'account.changePasswordBtn': 'Change Password',
    'account.saveChanges': 'Save Changes',
    'account.saving': 'Saving…',
    'account.addressesLoading': 'Loading addresses…',
    'account.selectAll': 'Select all',
    'account.deleteSelected': 'Delete selected',
    'account.edit': 'Edit',
    'account.addNewAddress': 'Add New Address',
    'account.defaultBadge': '(Default)',
    'account.setDefault': 'Set as default',
    'account.orderPrefix': 'Order',
    'account.productsUnit': 'product(s)',
    'account.viewDetails': 'View details →',
    'account.err.loadProfile': 'Could not load account details',
    'account.err.loadOrders': 'Could not load orders',
    'account.err.loadAddresses': 'Could not load addresses',
    'account.err.loadProvinces': 'Could not load provinces list',
    'account.err.phoneAddress': 'Phone must start with 0 and have exactly 10 digits',
    'account.err.pickProvince': 'Please select Province/City',
    'account.err.pickDistrict': 'Please select District',
    'account.err.pickWard': 'Please select Ward/Commune',
    'account.err.emailInvalid': 'Please enter a valid email address',
    'account.err.phoneProfile': 'Phone must start with 0 and have exactly 10 digits (e.g. 0912345678)',
    'account.err.emailFormat': 'Invalid email format',
    'account.success.profileSaved': 'Account details saved',
    'account.err.saveFailed': 'Could not save changes',
    'account.success.addressUpdated': 'Address updated',
    'account.success.addressAdded': 'Address added',
    'account.err.addressUpdateFailed': 'Could not update address',
    'account.err.addressAddFailed': 'Could not add address',
    'account.success.defaultSet': 'Default address updated',
    'account.err.defaultFailed': 'Could not set default address',
    'account.success.addressDeleted': 'Address deleted',
    'account.err.addressDeleteFailed': 'Could not delete address',
    'account.success.bulkDeleted': 'Deleted {{n}} addresses',
    'account.err.bulkPartial': 'Deleted {{ok}} addresses, {{fail}} failed',
    'account.dialog.editAddress': 'Edit address',
    'account.dialog.addAddress': 'Add new address',
    'account.field.receiver': 'Recipient',
    'account.field.addressLine': 'Address line',
    'account.field.province': 'Province/City',
    'account.field.district': 'District',
    'account.field.ward': 'Ward/Commune',
    'account.field.pickProvince': 'Choose Province/City',
    'account.field.pickDistrict': 'Choose District',
    'account.field.pickWard': 'Choose Ward/Commune',
    'account.field.searchProvince': 'Search province/city…',
    'account.field.searchDistrict': 'Search district…',
    'account.field.searchWard': 'Search ward…',
    'account.field.cmdEmpty': 'No results.',
    'account.checkbox.defaultAddress': 'Use as default delivery address',
    'account.dialog.updateBtn': 'Update',
    'account.dialog.addSubmitBtn': 'Add address',
    'account.confirm.deleteBulkTitle': 'Delete {{n}} addresses',
    'account.confirm.deleteTitle': 'Delete address',
    'account.confirm.deleteBulkDesc': 'Are you sure you want to delete {{n}} selected addresses?',
    'account.confirm.deleteDesc': 'Are you sure you want to delete this address?',
    'account.confirm.deleting': 'Deleting…',
    'account.ordersSearchPlaceholder': 'Search orders…',
    'account.ordersTabAll': 'All',
    'account.ordersTabProcessing': 'Processing',
    'account.ordersTabShipping': 'Shipping',
    'account.ordersTabDelivered': 'Delivered',
    'account.ordersEmpty': 'You have no orders yet',
    'account.ordersShopNow': 'Shop now',
    'account.retry': 'Try again',
    'account.paginationPrev': 'Previous',
    'account.paginationNext': 'Next',
    'account.paginationPage': 'Page',
    'account.orderStatus.waiting': 'Pending',
    'account.orderStatus.shipping': 'Shipping',
    'account.orderStatus.delivered': 'Delivered',
    'account.orderStatus.cancelled': 'Cancelled',

    'footer.subscribe': 'SUBSCRIBE',
    'footer.emailPlaceholder': 'EMAIL',
    'footer.subscribeThanks': 'Thank you for subscribing.',
    'footer.returnExchange': 'RETURN AND EXCHANGE POLICY',
    'footer.privacy': 'PRIVACY POLICY',
    'footer.instagram': 'INSTAGRAM',
    'footer.contact': 'CONTACT',
    'footer.copyright': '©VIVIENNE {year}',
  },
  vi: {
    // Header/Navigation
    'nav.allProducts': 'Tất cả sản phẩm',
    'nav.collections': 'Bộ sưu tập',
    'nav.about': 'Giới thiệu',
    'nav.signIn': 'Đăng nhập',
    'nav.signOut': 'Đăng xuất',
    'nav.myAccount': 'Tài khoản của tôi',
    'nav.myOrders': 'Đơn hàng của tôi',
    'nav.adminPanel': 'Quản trị viên',
    'nav.createAccount': 'Tạo tài khoản',
    'nav.cart': 'Giỏ hàng',
    'nav.search': 'Tìm kiếm',
    'nav.shopNav': 'CỬA HÀNG',
    'nav.collectionNav': 'BỘ SƯU TẬP',
    'nav.aboutNav': 'GIỚI THIỆU',
    'nav.searchNav': 'TÌM KIẾM',
    'nav.cartNav': 'GIỎ HÀNG',
    'nav.messengerNav': 'TIN NHẮN',
    'nav.accountNav': 'TÀI KHOẢN',
    'nav.logoutNav': 'ĐĂNG XUẤT',
    'nav.loginNav': 'ĐĂNG NHẬP',
    'nav.shopAll': 'TẤT CẢ',
    'nav.shopTops': 'ÁO KIỂU',
    'nav.shopShirts': 'SƠ MI',
    'nav.shopJackets': 'ÁO KHOÁC',
    'nav.shopSkirts': 'CHÂN VÁY',
    'nav.shopPants': 'QUẦN',
    'nav.shopAccessories': 'PHỤ KIỆN',
    
    // Login/Auth
    'auth.signIn': 'Đăng nhập',
    'auth.adminPortal': 'Cổng quản trị',
    'auth.accountName': 'Tên tài khoản',
    'auth.password': 'Mật khẩu',
    'auth.forgotPassword': 'Quên mật khẩu?',
    'auth.signingIn': 'Đang đăng nhập...',
    'auth.authenticating': 'Đang xác thực...',
    'auth.signInAsAdmin': 'Đăng nhập quản trị',
    'auth.adminLogin': 'Đăng nhập quản trị',
    'auth.adminLoginDesc': 'Đăng nhập để truy cập bảng điều khiển quản trị',
    'auth.backToUserLogin': '← Quay lại đăng nhập người dùng',
    'auth.needHelp': 'Cần hỗ trợ?',
    'auth.contactSupport': 'Liên hệ hỗ trợ',
    'auth.dontHaveAccount': 'Chưa có tài khoản?',
    'auth.createOne': 'Tạo tài khoản',
    'auth.email': 'Email',
    'auth.emailRequired': 'Email là bắt buộc',
    'auth.emailPlaceholder': 'Nhập địa chỉ email của bạn',
    'auth.forgotPasswordDesc': 'Nhập địa chỉ email của bạn và chúng tôi sẽ gửi cho bạn liên kết để đặt lại mật khẩu.',
    'auth.sendResetLink': 'Gửi liên kết đặt lại',
    'auth.sending': 'Đang gửi...',
    'auth.resetLinkSent': 'Liên kết đặt lại đã được gửi đến email của bạn',
    'auth.resetError': 'Không thể gửi liên kết đặt lại',
    'auth.backToLogin': 'Quay lại đăng nhập',
    'auth.backToAccount': 'Quay lại tài khoản',
    'auth.changePassword': 'Đổi mật khẩu',
    'auth.currentPassword': 'Mật khẩu hiện tại',
    'auth.newPassword': 'Mật khẩu mới',
    'auth.confirmPassword': 'Xác nhận mật khẩu',
    'auth.currentPasswordRequired': 'Mật khẩu hiện tại là bắt buộc',
    'auth.newPasswordRequired': 'Mật khẩu mới là bắt buộc',
    'auth.newPasswordMinLength': 'Mật khẩu mới phải có ít nhất 6 ký tự',
    'auth.confirmPasswordRequired': 'Xác nhận mật khẩu là bắt buộc',
    'auth.passwordMismatch': 'Mật khẩu không khớp',
    'auth.passwordChangeSuccess': 'Đổi mật khẩu thành công',
    'auth.passwordChangeError': 'Không thể đổi mật khẩu',
    'auth.changingPassword': 'Đang đổi mật khẩu...',
    'auth.sessionExpired': 'Phiên đăng nhập đã hết hạn, vui lòng đăng nhập lại',
    'auth.tokenRefreshed': 'Gia hạn phiên đăng nhập thành công',
    'auth.tokenRefreshFailed': 'Không thể gia hạn phiên đăng nhập',
    'auth.accountNamePlaceholder': 'Nhập tên tài khoản',
    'auth.passwordPlaceholder': 'Nhập mật khẩu',
    'auth.accountNameRequired': 'Vui lòng nhập tên tài khoản!',
    'auth.passwordRequired': 'Vui lòng nhập mật khẩu!',
    'auth.loginFailed': 'Đăng nhập thất bại!',
    'auth.welcomeBack': 'Chào mừng trở lại, {name}!',
    'auth.backToHome': '← Về trang chủ',
    
    // Logout Modal
    'logout.confirmTitle': 'Xác nhận đăng xuất',
    'logout.confirmMessage': 'Bạn có chắc chắn muốn đăng xuất không?',
    'logout.confirmButton': 'Đăng xuất',
    'logout.cancelButton': 'Hủy',
    'logout.success': 'Đăng xuất thành công',
    'logout.failed': 'Đăng xuất không thành công',
    'logout.signingOut': 'Đang đăng xuất...',
    
    // Admin
    'admin.dashboard': 'Bảng điều khiển',
    'admin.products': 'Sản phẩm',
    'admin.categories': 'Danh mục',
    'admin.orders': 'Đơn hàng',
    'admin.users': 'Người dùng',
    'admin.inventory': 'Kho hàng',
    'admin.shipping': 'Vận chuyển',
    'admin.promotions': 'Khuyến mãi',
    'admin.suppliers': 'Nhà cung cấp',
    'admin.content': 'Nội dung',
    'admin.messages': 'Tin nhắn',
    'admin.analytics': 'Phân tích',
    'admin.payments': 'Thanh toán',
    'admin.tracking': 'Theo dõi',
    'admin.reviews': 'Đánh giá',
    'admin.settings': 'Cài đặt',
    'admin.profileSettings': 'Cài đặt hồ sơ',
    
    // Categories
    'categories.title': 'Quản lý danh mục',
    'categories.addNew': 'Thêm danh mục mới',
    'categories.edit': 'Sửa danh mục',
    'categories.name': 'Tên danh mục',
    'categories.parent': 'Danh mục cha',
    'categories.position': 'Vị trí',
    'categories.status': 'Trạng thái',
    'categories.active': 'Hoạt động',
    'categories.inactive': 'Không hoạt động',
    'categories.actions': 'Thao tác',
    'categories.noParent': 'Không có danh mục cha (Danh mục chính)',
    'categories.createSuccess': 'Tạo danh mục thành công',
    'categories.updateSuccess': 'Cập nhật danh mục thành công',
    'categories.deleteSuccess': 'Xóa danh mục thành công',
    'categories.statusToggled': 'Cập nhật trạng thái danh mục thành công',
    'categories.confirmDelete': 'Bạn có chắc chắn muốn xóa danh mục này?',
    'categories.deleteWarning': 'Hành động này không thể hoàn tác.',
    'categories.nameRequired': 'Tên danh mục là bắt buộc',
    'categories.loading': 'Đang tải danh mục...',
    'categories.noCategories': 'Không tìm thấy danh mục nào',

    // Products
    'products.title': 'Quản lý Sản phẩm',
    'products.addNew': 'Thêm Sản phẩm Mới',
    'products.editProduct': 'Chỉnh sửa Sản phẩm',
    'products.deleteProduct': 'Xóa Sản phẩm',
    'products.name': 'Tên Sản phẩm',
    'products.slug': 'URL Slug',
    'products.description': 'Mô tả',
    'products.shortDescription': 'Mô tả Ngắn',
    'products.category': 'Danh mục',
    'products.brand': 'Thương hiệu',
    'products.material': 'Chất liệu',
    'products.status': 'Trạng thái',
    'products.featured': 'Nổi bật',
    'products.price': 'Giá',
    'products.stock': 'Tồn kho',
    'products.variants': 'Biến thể',
    'products.images': 'Hình ảnh',
    'products.actions': 'Thao tác',
    'products.active': 'Hoạt động',
    'products.inactive': 'Không hoạt động',
    'products.outOfStock': 'Hết hàng',
    'products.yes': 'Có',
    'products.no': 'Không',
    'products.confirmDelete': 'Bạn có chắc chắn muốn xóa sản phẩm này?',
    'products.deleteWarning': 'Hành động này không thể hoàn tác.',
    'products.save': 'Lưu',
    'products.cancel': 'Hủy',
    'products.delete': 'Xóa',
    'products.edit': 'Sửa',
    'products.view': 'Xem',
    'products.loading': 'Đang tải...',
    'products.noProducts': 'Không tìm thấy sản phẩm nào',
    'products.createSuccess': 'Tạo sản phẩm thành công',
    'products.updateSuccess': 'Cập nhật sản phẩm thành công',
    'products.deleteSuccess': 'Xóa sản phẩm thành công',
    'products.error': 'Đã xảy ra lỗi',
    'products.searchPlaceholder': 'Tìm kiếm sản phẩm...',
    'products.filterByCategory': 'Lọc theo Danh mục',
    'products.filterByStatus': 'Lọc theo Trạng thái',
    'products.sortBy': 'Sắp xếp theo',
    'products.sortByName': 'Tên',
    'products.sortByDate': 'Ngày tạo',
    'products.sortByPrice': 'Giá',
    'products.sortByStock': 'Tồn kho',
    'products.sortAsc': 'Tăng dần',
    'products.sortDesc': 'Giảm dần',
    'products.size': 'Kích thước',
    'products.color': 'Màu sắc',
    'products.sku': 'Mã SKU',
    'products.addVariant': 'Thêm Biến thể',
    'products.removeVariant': 'Xóa Biến thể',
    'products.addImage': 'Thêm Hình ảnh',
    'products.removeImage': 'Xóa Hình ảnh',
    'products.imageUrl': 'URL Hình ảnh',
    'products.altText': 'Văn bản Alt',
    'products.isPrimary': 'Hình ảnh Chính',
    'products.displayOrder': 'Thứ tự Hiển thị',
    'products.metaTitle': 'Meta Title',
    'products.metaDescription': 'Meta Description',
    
    // Common
    'common.loading': 'Đang tải...',
    'common.save': 'Lưu',
    'common.cancel': 'Hủy',
    'common.delete': 'Xóa',
    'common.edit': 'Sửa',
    'common.view': 'Xem',
    'common.close': 'Đóng',
    'common.submit': 'Gửi',
    'common.reset': 'Đặt lại',

    // Account (/account — Orders, Profile, Addresses)
    'account.title': 'Tài khoản',
    'account.tabOrders': 'Đơn hàng',
    'account.tabProfile': 'Hồ sơ',
    'account.tabAddresses': 'Địa chỉ',
    'account.firstName': 'Tên',
    'account.lastName': 'Họ',
    'account.email': 'Email',
    'account.phone': 'Điện thoại',
    'account.phoneHint': 'Tối đa 10 số, bắt đầu bằng 0 (ví dụ: 0912345678)',
    'account.emailPlaceholder': 'example@gmail.com',
    'account.passwordSection': 'Mật khẩu',
    'account.passwordChangeHint': 'Đổi mật khẩu cho tài khoản của bạn',
    'account.changePasswordBtn': 'Đổi mật khẩu',
    'account.saveChanges': 'Lưu thay đổi',
    'account.saving': 'Đang lưu…',
    'account.addressesLoading': 'Đang tải địa chỉ…',
    'account.selectAll': 'Chọn tất cả',
    'account.deleteSelected': 'Xóa đã chọn',
    'account.edit': 'Sửa',
    'account.addNewAddress': 'Thêm địa chỉ mới',
    'account.defaultBadge': '(Mặc định)',
    'account.setDefault': 'Đặt làm mặc định',
    'account.orderPrefix': 'Đơn',
    'account.productsUnit': 'sản phẩm',
    'account.viewDetails': 'Xem chi tiết →',
    'account.err.loadProfile': 'Không tải được thông tin tài khoản',
    'account.err.loadOrders': 'Không tải được đơn hàng',
    'account.err.loadAddresses': 'Không tải được địa chỉ',
    'account.err.loadProvinces': 'Không tải được danh sách tỉnh/thành phố',
    'account.err.phoneAddress': 'Số điện thoại phải bắt đầu bằng 0 và có đúng 10 chữ số',
    'account.err.pickProvince': 'Vui lòng chọn Tỉnh/Thành phố',
    'account.err.pickDistrict': 'Vui lòng chọn Quận/Huyện',
    'account.err.pickWard': 'Vui lòng chọn Phường/Xã',
    'account.err.emailInvalid': 'Vui lòng nhập đúng định dạng email',
    'account.err.phoneProfile': 'Số điện thoại phải bắt đầu bằng 0 và có đúng 10 chữ số (ví dụ: 0912345678)',
    'account.err.emailFormat': 'Email không đúng định dạng',
    'account.success.profileSaved': 'Đã lưu thông tin tài khoản',
    'account.err.saveFailed': 'Không thể lưu thay đổi',
    'account.success.addressUpdated': 'Đã cập nhật địa chỉ',
    'account.success.addressAdded': 'Đã thêm địa chỉ',
    'account.err.addressUpdateFailed': 'Không thể cập nhật',
    'account.err.addressAddFailed': 'Không thể thêm địa chỉ',
    'account.success.defaultSet': 'Đã đặt làm địa chỉ mặc định',
    'account.err.defaultFailed': 'Không thể đặt địa chỉ mặc định',
    'account.success.addressDeleted': 'Đã xóa địa chỉ',
    'account.err.addressDeleteFailed': 'Không thể xóa địa chỉ',
    'account.success.bulkDeleted': 'Đã xóa {{n}} địa chỉ',
    'account.err.bulkPartial': 'Đã xóa {{ok}} địa chỉ, {{fail}} lỗi',
    'account.dialog.editAddress': 'Chỉnh sửa địa chỉ',
    'account.dialog.addAddress': 'Thêm địa chỉ mới',
    'account.field.receiver': 'Người nhận',
    'account.field.addressLine': 'Địa chỉ',
    'account.field.province': 'Tỉnh/Thành phố',
    'account.field.district': 'Quận/Huyện',
    'account.field.ward': 'Phường/Xã',
    'account.field.pickProvince': 'Chọn Tỉnh/Thành phố',
    'account.field.pickDistrict': 'Chọn Quận/Huyện',
    'account.field.pickWard': 'Chọn Phường/Xã',
    'account.field.searchProvince': 'Tìm tỉnh/thành phố…',
    'account.field.searchDistrict': 'Tìm quận/huyện…',
    'account.field.searchWard': 'Tìm phường/xã…',
    'account.field.cmdEmpty': 'Không tìm thấy.',
    'account.checkbox.defaultAddress': 'Đặt làm địa chỉ mặc định',
    'account.dialog.updateBtn': 'Cập nhật',
    'account.dialog.addSubmitBtn': 'Thêm địa chỉ',
    'account.confirm.deleteBulkTitle': 'Xóa {{n}} địa chỉ',
    'account.confirm.deleteTitle': 'Xóa địa chỉ',
    'account.confirm.deleteBulkDesc': 'Bạn có chắc muốn xóa {{n}} địa chỉ đã chọn?',
    'account.confirm.deleteDesc': 'Bạn có chắc muốn xóa địa chỉ này?',
    'account.confirm.deleting': 'Đang xóa…',
    'account.ordersSearchPlaceholder': 'Tìm đơn hàng…',
    'account.ordersTabAll': 'Tất cả',
    'account.ordersTabProcessing': 'Đang xử lý',
    'account.ordersTabShipping': 'Đang giao',
    'account.ordersTabDelivered': 'Đã giao',
    'account.ordersEmpty': 'Chưa có đơn hàng nào',
    'account.ordersShopNow': 'Mua sắm',
    'account.retry': 'Thử lại',
    'account.paginationPrev': 'Trước',
    'account.paginationNext': 'Sau',
    'account.paginationPage': 'Trang',
    'account.orderStatus.waiting': 'Chờ xử lý',
    'account.orderStatus.shipping': 'Đang giao',
    'account.orderStatus.delivered': 'Đã giao',
    'account.orderStatus.cancelled': 'Đã hủy',

    'footer.subscribe': 'ĐĂNG KÝ',
    'footer.emailPlaceholder': 'EMAIL',
    'footer.subscribeThanks': 'Cảm ơn bạn đã đăng ký.',
    'footer.returnExchange': 'CHÍNH SÁCH ĐỔI TRẢ',
    'footer.privacy': 'CHÍNH SÁCH BẢO MẬT',
    'footer.instagram': 'INSTAGRAM',
    'footer.contact': 'LIÊN HỆ',
    'footer.copyright': '©VIVIENNE {year}',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('vi')

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'vi')) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
